---
- name: Setup | Debian | Enable lib32.
  lineinfile:
    path: /var/lib/dpkg/arch
    regexp: "^i386"
    line: "i386"
    mode: "0644"
    create: yes
  when: setup_lib32 | bool

- name: Setup | Debian | Enable contrib repo.
  apt_repository:
    repo: deb http://deb.debian.org/debian "{{ ansible_distribution_release }}" contrib
    state: present
  when: setup_repo_contrib | bool

- name: Setup | Debian | Enable non-free-firmware repo.
  apt_repository:
    repo: deb http://deb.debian.org/debian "{{ ansible_distribution_release }}" non-free-firmware
    state: present
  when: setup_repo_nonfreefirmware | bool

- name: Setup | Debian | Enable non-free repo.
  apt_repository:
    repo: deb http://deb.debian.org/debian "{{ ansible_distribution_release }}" contrib non-free-firmware
    state: present
  when: setup_repo_nonfree | bool

# TODO: Add backports

- name: Setup | Debian | Refresh apt.
  apt: update_cache=yes

- name: Setup | Debian | Install non-free firmware.
  apt:
    name:
      - firmware-linux
      - firmware-linux-nonfree
      - firmware-misc-nonfree
  when: install_firmware_nonfree | bool

- name: Setup | Debian | Install essential packages.
  apt:
    name:
      - build-essential
      - dkms
      - gettext
      - "linux-headers-{{ ansible_kernel }}"
      - software-properties-common
    state: present
  when: install_buildpkgs | bool

- name: Setup | Debian | Install nala (apt wrapper).
  apt:
    name: nala
    state: present
  when: install_nala | bool
