---
- name: Setup | Multimedia | Ensure multimedia codecs
  package:
    name:
      - "{{ gstreamer_libav_package }}"
      - "{{ gstreamer_plugins_bad_package }}"

- name: Multimedia | Ensure mpv is installed.
  package:
    name: mpv
    state: present
  when: mpv | bool
